### ISSUE TITLE
Rendering component in infoBox doesn't render Link href

### ISSUE THREAD

**Issue by corbpaul** [tomchentw/react-google-maps#258] opened 2016-05-16 09:21 UTC
I'm passing a component into an infoBox:

`<InfoBox><Component model={model} /></InfoBox>`

Within that component is a `Link` from `react-router` :

`<Link to={model.url}>url</Link>`

but when the infoBox is displayed the `a` tag renders in the DOM without a href

**Comment by corbpaul** [comment] 2016-05-17 01:09
Also tested using `<Link to='/'>url</Link>` in the `<InfoBox>` component and that does exactly the same

**Comment by corbpaul** [comment] 2016-05-18 01:48
@wuct any ideas why this may be?

**Comment by wuct** [comment] 2016-05-18 05:51
`<Link />` [expects a `router` in the `context`](https://github.com/reactjs/react-router/blob/master/modules%2FLink.js#L113-116). Without it, `<Link />` do not generate a `href` attribute.

AFAIK `< InfoBox />` or other `react-google-maps`  components does not pass their owners `context` to their children, because  `react-google-maps` [renders in a different context internally](https://github.com/tomchentw/react-google-maps/blob/5e672b92f3e47861126349a5691c33b9b1d1eb88/src%2Futils%2FsetContentForOptionalReactElement.js#L19).

A quick fix would be setting `href` directly to `<Link />

```JavaScript
 <Link href={mode.url} />
```

A better solution would be making `react-google-maps` handle `context` properly. @tomchentw How do you think?

**Comment by tomchentw** [comment] 2016-05-29 03:09
Since we now have major adoption for `react@^0.14`, we should be able to fix this.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by benwiley4000** [comment] 2016-06-17 04:38
@tomchentw I do not see why you closed this issue, please reopen it - it is still outstanding, I was about to post the same! Context should be passed, but it lost because children are rendered using ReactDom.render. Look into [renderSubtreeIntoContainer](https://github.com/gaearon/react-dnd/issues/204#issuecomment-114476147). It's a means to passing context to manual React rendering. I was going to try submitting a PR myself, but I'm still trying to digest the code base. I was hoping you or someone else closely involved in the project might be able to provide a quick patch.

**Comment by benwiley4000** [comment] 2016-06-17 05:48
Note that @wuct's tentative solution of setting `href` directly is not a complete fix. First off, it causes a page reload. Second, in certain cases, the transition will be blocked and default prevented (in my particular case, it seems anytime the map route is not the initially loaded route fetched from the server).

Long story short - those are not problems I should need to debug, since react-google-maps should be passing `context`. :smiley:

For now, I'm falling back to `<a>` tags, which force a page reload, but also don't break.

**Comment by brandonmp** [comment] 2016-09-08 01:14
@benwiley4000  did you figure this out?

is it possible to set the route from the parent and pass the handler down to the infoWindow?

I'm able to execute redux actions from the infoWindow by doing that, but I don't know too much about React Router, so uncertain if same applies

**Comment by benwiley4000** [comment] 2016-09-08 01:21
@brandonmp: I probably could pass an action down, but I would like to be able to use React Router's `Link` component rather than specifying an `onClick` route change explicitly.

**Comment by brandonmp** [comment] 2016-09-08 01:24
word, but a bird in hand & all that

the real bummer for me is i can't use MUI components as they require context. haven't found a workaround for that yet.

**Comment by tomchentw** [comment] 2016-10-06 03:41
@benwiley4000 @corbpaul @brandonmp

I'm sorry to close this but it would be great if you can help! Yes you are right we should switch to `ReactDOM.unstable_renderSubtreeIntoContainer` to preserve context.

Do you want to open up a PR for this? Just to let you know, we just released [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) and it's rewritten from scratch. I hope this could help you understand the code base faster.

It'ss released on npm beta tag. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by benwiley4000** [comment] 2016-10-06 03:51
@tomchentw thanks for the update. I'm adding this to my todo list and I'll look at it soon. :)

**Comment by benwiley4000** [comment] 2016-10-12 21:25
@tomchentw I've completed a fix that uses `ReactDOM.unstable_renderSubtreeIntoContainer`. Should the `lib` changes be included in the PR, or only the source changes?

**Comment by benwiley4000** [comment] 2016-10-12 21:30
Addressed by https://github.com/tomchentw/react-google-maps/pull/361.

**Comment by tomchentw** [comment] 2016-10-14 06:22
Closed by #361 , thanks @benwiley4000 !

**Closed by tomchentw** 2016-10-14 06:22 UTC

**Comment by tomchentw** [comment] 2016-10-14 06:27
Released [v6.0.1](https://github.com/tomchentw/react-google-maps/releases/tag/v6.0.1) in the npm `beta` channel.

**Comment by stupidisum** [comment] 2016-10-17 05:34
How about OverlayView and maybe other components?

**Comment by benwiley4000** [comment] 2016-10-17 05:43
@stupidisum good catch, didn't notice that when I was working on the pull request because child rendering works a bit differently than `InfoWindow`/`InfoBox`. I could submit another change if you'd like?

**Comment by iamdavidmartin** [comment] 2018-01-15 01:27
Has this issue cropped back up again with react router v4? All my Links work without causing a page reload except for the ones inside the InfoBox. For me replicating the issue is as simple as a Link inside an InfoBox, clicking it, and the link is followed like a traditional anchor tag.

Perhaps a Link will never work in the InfoBox due to the event propagation?

I created a stack-overflow about this as well but no responses. https://stackoverflow.com/questions/48234933/link-in-infobox-using-react-google-maps-causes-page-reload

**Comment by nabeel-akram** [comment] 2018-08-07 15:33
i'm facing same issue. i've a menu inside the InfoBox. And each menu item has a Link. Clicking on a menu item is causing a reload.
Also onClick event is not working inside InfoBox. I've set enableEventPropagation: true, but still can't trigger onClick from children components of InfoBox.
