### ISSUE TITLE
How to stop propagation of events from OverlayView to Map?

### ISSUE THREAD

**Issue by EPecherkin** [tomchentw/react-google-maps#84] opened 2015-07-30 09:42 UTC
I have some overlay views with react content on map. Content have onClick handlers.
Also I have onClick handler on map.
When I click on overlay view content map receive click too.
As I noticed, map receive click event first. And second is overlay view.
And is is the problem.

**Comment by ksavenkov** [comment] 2015-10-09 19:34
Second that. As I understand, this is not the intended behavior of Google Maps. It breaks the use case when OverlayView is used to display a menu, which is closed by clicking on the map.

**Comment by ksavenkov** [comment] 2015-10-09 20:07
Actually, I've found a workaround: added overlayHovered flag to the state and check it in handleMapClick function.

**Comment by tomchentw** [comment] 2015-10-11 14:18
I've noticed the same behavior in the [#basics/overlay-view](https://tomchentw.github.io/react-google-maps/#basics/overlay-view) example.

**Comment by juankahuna** [comment] 2016-05-14 21:24
Having the same issue here, was there a better solution for this?

**Comment by tomchentw** [comment] 2016-05-29 09:28
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Closed by tomchentw** 2016-05-29 09:28 UTC
Labels: bug, enhancement, help wanted

**Comment by urikphytech** [comment] 2017-07-12 08:33
Anyone find a good solution for this?

**Comment by tomhalley** [comment] 2018-08-02 13:28
[This seems to be a bug inherent in google maps.](https://issuetracker.google.com/issues/35819207)

[One guy said he found a fix](https://shades-of-orange.com/post/Stop-Propagation-of-Google-Maps-Marker-Click-Event-a-Solution!), but that didn't work for me...

And the hover solution suggested by @ksavenkov and another guy in [this stackoverflow thread](https://stackoverflow.com/questions/43807586/rendering-react-component-into-googlemaps-infobox-stop-click-throughs) doesn't work on mobile, so not a long term fix.

I've had to deal with this issue a year ago, and now coming back to it again. I think it's getting to a point where I'd pay money

**Comment by ufon** [comment] 2018-08-04 18:46
up please

**Comment by madrussa** [comment] 2018-08-08 11:00
I've found a solution that seems to work nicely using the static preventMapHitsFrom and preventMapHitsAndGesturesFrom methods from https://developers.google.com/maps/documentation/javascript/reference/overlay-view#OverlayView.preventMapHitsFrom

In your component or HTML Element within your OverlayView you can call preventMapHitsFrom on your element that you don't want your mouse or touch events filtering down to the map
```jsx
class OverlayInner extends React.Component {
  handleClick = () => {
    console.log('I still work');
  }
  render () {
    <div
      ref={ ref => ref && google.maps.OverlayView.preventMapHitsFrom(ref) }
      onClick={this.handleClick}
    />
      Dont click map
    </div>
  }
}
```
Your standard onClick events will continue to work.

**Comment by tomhalley** [comment] 2018-08-08 13:45
Wow... is that new @madrussa? That's worked perfectly.

I spent over a year looking for a fix for that...

![Damn...](https://i.kym-cdn.com/photos/images/newsfeed/001/373/328/b16.jpg)

**Comment by madrussa** [comment] 2018-08-08 14:53
Yeah it looks new. I can see it in 3.33 but not 3.32. My only concern is that it's a black hole and it could lead to memory leaks... as you feed it references, but what happens when they remove?
